### ISSUE TITLE
Does not gracefully handle long secrets

### ISSUE THREAD

**Issue by Victor-OFC** [open-function-computers-llc/secret-share#20]
This picture says it all =)
Text is overflowing outside text field to the right and below
![image](https://user-images.githubusercontent.com/93009999/222313506-9e604ae0-d154-4a8f-8a21-483f5de27150.png)

**Comment by lapubell** [comment]
should be good to go!
![image](https://user-images.githubusercontent.com/7433452/223862272-5b030a4b-5514-47f4-a19a-05aa7392b9d1.png)
